name: black

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: black
        uses: jpetrucciani/black-check@master
        with:
          path: "."
